[metadata]
name = neutron-flavor-qos
summary = Neutron service plugin for Nova flavor based port QoS enforcement
description_file =
    README.md
author = OpenStack
python_requires = >=3.10
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[files]
packages =
    neutron_flavor_qos

[entry_points]
neutron.service_plugins =
    flavor_qos = neutron_flavor_qos.plugin:FlavorQosServicePlugin
oslo.config.opts =
    neutron_flavor_qos = neutron_flavor_qos.config:list_opts
