[tox]
envlist = py3,pep8
minversion = 3.18.0
skipsdist = False
ignore_basepython_conflict = True

[testenv]
basepython = {env:TOX_PYTHON:python3}
usedevelop = True
deps =
  -r{toxinidir}/requirements.txt
commands =
  python -m unittest discover tests/unit

[testenv:pep8]
commands =
  python -m compileall neutron_flavor_qos tests
